#define OP_NUM_RET				1
#define OP_NUM_BR				2
#define OP_NUM_SWITCH			3
#define OP_NUM_INVOKE			4
#define OP_NUM_UNWIND			5
#define OP_NUM_UNREACHABLE		6
#define OP_NUM_ADD				7
#define OP_NUM_SUB				8
#define OP_NUM_MUL				9
#define OP_NUM_DIV				10
#define OP_NUM_REM				11
#define OP_NUM_AND				12
#define OP_NUM_OR				13
#define OP_NUM_XOR				14
#define OP_NUM_SETEQ			15
#define OP_NUM_SETNE			16
#define OP_NUM_SETLE			17
#define OP_NUM_SETGE			18
#define OP_NUM_SETLT			19
#define OP_NUM_SETGT			20
#define OP_NUM_MALLOC			21
#define OP_NUM_FREE			22
#define OP_NUM_ALLOCA			23
#define OP_NUM_LOAD			24
#define OP_NUM_STORE		25
#define OP_NUM_GETELEMENTPTR	26
#define OP_NUM_PHI				27
#define OP_NUM_CAST			28
#define OP_NUM_CALL			29
#define OP_NUM_SHL				30
#define OP_NUM_SHR				31
#define OP_NUM_VANEXT			32
#define OP_NUM_VAARG			33
#define OP_NUM_SELECT			34
